on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  backup-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar ferramentas necessárias
        run: |
          sudo apt update
          sudo apt install -y tar coreutils grep

      - name: Executar backup
        run: bash backup.sh

      - name: Analisar logs
        run: bash log_scan.sh

      - name: Salvar arquivos de backup
        uses: actions/upload-artifact@v4
        with:
          name: arquivos-de-backup
          path: backups_projeto_log_monitor/

      - name: Salvar relatórios com artefato
        uses: actions/upload-artifact@v4
        with:
          name: backup-log-reports
          path: reports
